import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'NextJs Shadcn TS',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='min-h-screen font-poppins bg-black-100'>{children}</body>
    </html>
  )
}
